name: dev-release
on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test:cov
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          file: ./coverage/clover.xml
          fail_ci_if_error: true

  # release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@master
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@latest
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
  #         body: |
  #           Changes in this Release
  #           - First Change
  #           - Second Change
  #         draft: false
  #         prerelease: false

  # build-and-deploy:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       node-version: [8.x, 10.x, 12.x, 14.x]
  #       os: [windows-latest, macos-latest, ubuntu-latest]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2.3.1
  #       with:
  #         persist-credentials: false
  #     - name: Install and Build
  #       run: |
  #         npm install
  #         npm run docs:build

  #     - name: Deploy
  #       uses: JamesIves/github-pages-deploy-action@4.1.6
  #       with:
  #         BRANCH: gh-pages
  #         FOLDER: docs/.vuepress/dist
  #       env:
  #         CI: true
